version: 2.1

# Pipeline parameters
parameters:
  environment:
    type: enum
    enum: ["staging", "production"]
    default: "staging"

# Define the jobs
jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0  # Example build environment
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            echo "Installing dependencies..."
            # Add your dependency installation command here
      - run:
          name: Run Unit Tests
          command: |
            echo "Running unit tests..."
            # Replace with your actual test command
            echo "Tests completed successfully!"

  deploy:
    docker:
      - image: cimg/openjdk:11.0  # Example deployment environment
    parameters:
      environment:
        type: enum
        enum: ["staging", "production"]
    steps:
      - run:
          name: Echo Deployment Environment
          command: echo "Deploying to << parameters.environment >> environment."
      - when:
          condition: << parameters.environment >> == "production"
          steps:
            - run:
                name: Run Production-Specific Tasks
                command: |
                  echo "Running additional tasks for production environment..."
                  # Add production-specific commands here
      - run:
          name: Finalize Deployment
          command: echo "Deployment complete!"

# Define the workflow with branch filters and parameters
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build  # The build job always runs
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
          environment: << pipeline.parameters.environment >>
